server:
  port: 8080

spring:
  application:
    name: groupwatch
  session:
    store-type: none

eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 10
  client:
    serviceUrl:
      defaultZone: http://service-discovery:8761/eureka/
    security:
      basic:
         enabled: false

ribbon:
  ServerListRefreshInterval: 1000

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true

management:
  port: 8081
  address: 0.0.0.0